---
    - name: Update and upgrade Ubuntu
      apt:
        update_cache: yes


    - name: Install required packages for containerd
      apt:
        name:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: docker compose copy file
      copy:
        src: docker-compose.prod.yml
        dest: .
    
    - name: docker compose up
      command: docker compose -f docker-compose.prod.yml up -d
